### Neural Networks

## Non-linear hypotheses
# If a hypothesis is very complicated with a non-intuitive fit, a proper...
# ...regression specification will be computationally expensive and lead to...
# ...overfitting

## Neural Networks Introduction
# Machine learning engineers decided to design algorithms that mimic the brain
# Example: blind humans snapping their fingers and moving based on sonar...
# ...learning to move better with more experience
# Popular in the eighties and nineties but lost popularity, resurged with...
# ...recent innovations

## Model Representation
# A neuron takes a sense input and maps it to an output corresponding to a...
# ...concluding decision category 
# In the logistic unit, a set of inputs are mapped to a sigmoid activation...
# ...function where at each neuron, a value is added to the logistic...
# ...function if that variable is present for that pass through
# This means that truth tables can be set up so that the logistic function...
# ...concludes that something is present iff certain not necessarily...
# ...linear criteria are met
# A neural network has a layer of neurons that interact to result in an output
# Neural networks have i input & hidden units where the hidden & input units...
# ...interact until the estimation occurs with the input layer after enough...
# ...iterations
# At the top of each layer is a "bias unit" that impacts other parameters...
# ...but is not impacted in return by other neurons; this is effectively...
# ...a constant that impacts the "truth table" output in a strategically...
# ...chosen way
# A neural network with just 1 layer is analogous to simple logistic...
# ...regression, but the fit is determined via non-linear assignment 

## Multiclass Classification
# If there are more than 2 outcomes (e.g. is the image a truck? a car? a...
# ...person?), there are as many possible outcome vectors as there are...
# ...categories, and each outcome vector is a 0 vector except for one 1...
# ...iff that index element is what the neural network concludes

