%%% Anomaly Detection

%% Motivation
% Anomaly detection borrows facets from both supervised & unsupervised learning
% Anomaly detection tests whether a "test" observations differs substantially...
% ...from teh training observations
% Anomaly detection tests for defective products based on trained data
% If the probability of observing the test observation is less than a...
% ...threshold parameter, flag as an anomaly
% Fraud detection is an application of anomaly detection 

%% Gaussian Distribution
% When an observation has one variable of output, a Gaussian distribution...
% ...can be fitted (typically good if most values are clustered in the...
% ...middle, with some spread out outliers)

%% Algorithm
% 1) Choose features x(i) that will help predict anomalous examples
% 2) Calculate the mean & variance of each feature 
% 3) Calculate the probability that you observed the feature value equaling...
% ...as you did for each feature of the test obs; multiply all of these...
% ...values and classify test obs as anomaly if probability is lower than...
% ...the set threshold (epsilon)
% This method effectively says that there is a cluster around all of the...
% ...points that are non-anomalous, but once this space is exited, it must...
% ...mean that the observation has anomalous values too far from the center...
% ...of the features' distributions

%% Developing & Evaluating Anomaly Detection Algorithms
% Real number evaluation means making decisions by breaking an ML algorithm's...
% ...performance down by a real number which conveys performance
% Anomaly detection algorithms take all non-anomalous observations and put...
% ...them in the training set, while a few anomalous observations will be in...
% ...the CV & test set 
% Placing no anomalies in the training set allow Gaussians of non-anomalous...
% ...data to be fitted
% The CV set can help set the threshold parameter
% Precision/recall are better evaluation metrics than classification accuracy...
% ...because of the bias towards negative classes (few anomalies relatively)

%% Comparison to Supervised Learning
% If data are labeled, supervised learning (e.g. neural net or logistic)...
% ...could be preferable to anomaly detection 
% Anomaly detection is preferable if there are not many anomalies to train...
% ...from, so it could be hard to train the data to detect new anomalies, so...
% ...just use the Gaussian distribution from anomaly detection
% Example: there are many different types of SPAM emails (tends towards...
% ...anomaly detection), but supervised learning can be used because there...
% ...is enough data to train from
% Anomaly detection is used when the amount of anomalies in the data are...
% ...proportionally quite small (e.g. fraud detection)

%% Selection of Features
% Check to make sure the data are Gaussian to check that assumption
% If data are not Gaussian, execute some logical transformations (e.g. log)
% Choose features that take on very large or small values if anomalous

%% Multivariate Gaussian
% It is possible to model data using a multivariate Gaussian; this works well...
% ...if correlations need to be captured, but does not scale well & fails if...
% ...the training set is smaller than the number of features
% Correlations can be captured with the traditional Gaussian model by...
% ...manufacturing new features that capture their correlation
% Multivariate Gaussian & the traditional method are equivalent iff the...
% ...covariances of the features are 0













