%%% Recommender Systems

%% Motivation
% Recommender systems have little interest in academia compared to business
% Example: Which movie should a user be suggested to watch next?

%% Problem Formulation
% Parameters for recommender systems for movies include:
%   1) # of users 
%   2) # of movies
%   3) whether a movie was rated by the user
%   4) what the movie was rated by the user (undefined if not rated)

%% Content Based Recommendation
% Define different features (e.g. what % a movie is romantic, action, etc)...
% ...for each movie and fit a regularized linear regression for each user 
% For each user, this regression associates highly rated movie categories...
% ...with a high probability of having movies predicted with those percents...
% ...of movie mixture
% This formulation assumes that movies have well defined features

%% Collaborative Filtering
% Unlike content based recommendation, collaborative filtering does not need...
% ...features because it learns them
% Collaborative filtering creates a vector for each user showing how much...
% ...they enjoy a certain category of movies, then goes back and categorizes...
% ...the movies based on how these users rated them 
% Collaborative filtering tries to minimize the sum of squares of how a...
% ...customer would rank a movie compared to how they actually ranked it
% Collaborative filtering is collaborative/iterative; given movie ratings,...
% ...use initialized movie classifications to estimate consumer preferences,...
% ...then use the estimated consumer preferences to estimate the movie...
% ...classifications, and so on
% There is no intercept in the collaborative filtering algorithm, that...
% ...feature would be learned if it was necessary
% Random initialization of the x vectors (movie values) & theta vectors...
% ...(user values) are required (see 7:30 of "collaborative filtering...
% ...algorithm" for the remaining gradient descent algorithm for recommenders)

%% Low Rank Matrix Factorization
% The score of movie i for user j is the sum product of the movie's...
% ...scores for each feature with the respective user's parameters (vectorized)
% If the distance between the x vectors of movies i & j is small, then the...
% ...movies are "similar" (the feature values for each movie are similar)
% If you have a user with no movies rated, execute mean normalization...
% ...(assign a score for each movie to that user equal to its mean from other...
% ...users)
% If a movie has no ratings, it should probably be discarded from recommendation
