%%% Machine Learning System Design

%% Building a Spam Classifier 
% In machine learning, it is best to start with a simple algorithm & cross...
% ...validate, then plot learning curves to determine what will improve and...
% ...then examine the cross validation set to see how the errors occur 
% Error analysis is the manual assessment of which prediction errors occur...
% ...the most, questioning why, and improving the learning algorithm accordingly
% Manual analysis gives a good insight into the nature of the data & algorithm
% Numerical evaluation is key; this is the process of evaluating an...
% ...algorithm's accuracy by using an objective real number measure, more...
% ...efficient than manual evaluation 
% Can use stemming software for text data; this is treating words that have...
% ...the same first n letters as the same word (e.g. porter stemmer)

%% Handling Skewed Data
% A class is skewed if it is dominated by an outcome (e.g. 0.5% of patients...
% ...have cancer)
% If 0.5% of patients have cancer, then 99% accuracy is not great because...
% ...you would get 99.5% accuracy from just guessing no cancer 
% An algorithm's precision is the probability that someone predicted to have...
% ...cancer actually has cancer (true pos / (true pos + false pos))
% An algorithm's recall is the probability someone with cancer will be...
% ...predicted to have cancer (true pos / (true pos + false neg))
% Imagine a patient was predicted to have cancer iff the probability of...
% ...cancer exceeded threshold T
% a. For larger T, precision increases because we are more confident that a...
% ...diagnosed patient has cancer since they were classified in face of a...
% ...higher threshold, recall falls because it is harder for the cancer...
% ...patients to actually be diagnosed beyond the threshold
% b. For smaller T, precision falls because it becomes easier to incorrectly...
% ...classify someone has having cancer, while recall rises because more...
% ...subjects are diagnosed 
% When selecting between algorithms using precision-recall, it is best to not...
% ...average because just predicting 1 will inflate the recall since every...
% ...positive/cancerous case will be predicted. Instead, use the F1 score by...
% ...doubling the product of precision & recall and dividing by precision and...
% ...recall
% A threshold for a classifier can be chosen by maximizing the F1 score 

%% Large Data
% Making the decision to increase model performance by increasing data &...
% ...improving the model depends on the context of the ML problem 
% More data is better to more features if already enough features to...
% ...sufficiently predict y (could a human expert predict with this info)?
% Having comprehensive features tends to low bias by not missing fit
% Having large observation # tends to low variance by not allowing overfitting     
