%%% Clustering

%% Unsupervised Learning Overview
% Unsupervised learning finds structure between data that do not belong...
% ...to an outcome class (just characteristics x without outcome label y)
% Clustering groups data together, having many applications including social...
% ...network collections & market segmentation

%% K-Means Clustering Algorithm
% K-Means breaks a dataset into k clusters iteratively
% Repeat the following steps an inputted parameter # of times:
% 1) Take randomly initialized cluster centroids & find which cluster...
% ...centroid each point is closest to 
% 2) Move each cluster centroid to the center (average) of all points where...
% ...its the closest to
% No need for an intercept term in clustering because not fitting to an...
% ...outcome label y
% If there is a cluster centroid with no points assigned to it, then it can...
% ...be eliminated (k - 1) cluster, or reinitialized
% The k-means obj func is to minimize the squared distance between each...
% point & its respective cluster centroid 
% The k-means cost function is the "distortion function", which measures the...
% ...distance between each centroid & its respective points
% It's not possible for the distortion function to increase over iterations,...
% ...but it is possible to get stuck in local optima
% K should always be less than m (you can't have more clusters than training...
% ...examples)
% Initialize K arbitrary training examples as the cluster centroids 
% To avoid local optima (not best clustering based on distortion function),...
% ...try k-means with multiple different initializations & find the...
% ...clustering that minimizes the distortion function
% For large K, multiple random initializations becomes less important 
% Choosing the number of clusters is difficult & appears subjective
% The elbow method says to pick the number of clusters where the distortion...
% ...function no longer drops as rapidly as before
% Sometimes K-means can be judged for the ability to optimize a later purpose