%%% Logistic Regression Cost Function
% Logistic regression taking the same cost function as linear regression is...
% ...poor because the cost function will be non-convex, meaning that gradient...
% ...descent may converge to a non-global optima
% The logistic regression cost function (in Cost Function video) is piecewise...
% ...depending on whether the actual value of the training set is 0 or 1, but...
% ...both cases have an accurate guess having 0 cost while an inaccurate...
% ...guess imposes a cost that limits towards infinity

%%% Simplified Cost Function & Gradient Descent
% It is possible to combine the piecewise cost function above so it is...
% ...expressed as one function
% The cost function is derived from maximum likelihood estimation and is convex
% The gradient descent derivation & update is in the gradient descent video
% Gradient descent updates actually looks equivalent for linear/logistic...
% ...regression, but differs because the hypothesis has changed for...
% ...classification
% Feature scaling also speeds up the logistic regression gradient descent...
% ...algorithm