%%% Multiclass Classification
% Multiclass classification classifies outcomes into 3 or more outcomes
% Example: is the weather snowy, rainy, or sunny?
% One-vs-all/rest classification creates a new training set for each outcome...
% ...that trains the probability outcome belongs to a certain class; after...
% ...running each regression, assign the observation to the outcome with...
% ...which it has the highest calculated probability 
% If there are k groups, then one-vs-all classification requires k estimations
